name: Deploy-Project
on: push
jobs:
    Lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Install Modules
              run: yarn  
            - name: Lint Code
              run: eslint --ext .jsx --fix src
    Test-job:
        needs: Lint-job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Test Code
              run: vitest run
    Build-job:
        needs: Test-job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Build Code
              run: vite build
